dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: %ROOT%
    train_path: %TRAIN_CONLLX%
    dev_path: %DEV_CONLLX%
    test_path: %TEST_CONLLX%
  embeddings:
    type: subword #{token,subword}
    root: %ROOT%
    train_path: %TRAIN_CONLLX%.%MODEL%.hdf5
    dev_path: %DEV_CONLLX%.%MODEL%.hdf5
    test_path: %TEST_CONLLX%.%MODEL%.hdf5
  batch_size: 20
model:
  hidden_dim: 1024 # ELMo hidden dim
  model_name: %MODEL%
  #embedding_dim: 1024 # ELMo word embedding dim
  model_type: BERT-disk # BERT-disk, ELMo-disk, 
  use_disk: True
  model_layer: %LAYER%
probe:
  task_signature: word # word, word_pair
  task_name: parse-depth
  maximum_rank: 1024
  psd_parameters: True
  diagonal: False
  params_path: predictor.params
probe_training:
  epochs: 40
  loss: L1
reporting:
  root: %ROOT%/%MODEL%_%LAYER%
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
    - image_examples
    - root_acc
